apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql-operator

resources:
- namespace.yaml
- configmap.yaml
# - operator-service-account-rbac.yaml
- operator-service-account-rbac-openshift.yaml
- scc.yaml
- postgres-operator.yaml
- api-service.yaml
